title: "[General]"
labels: ["General Introduction"]
body:
  - type: markdown
    attribute :
      value : | 
        # 💡 아이디어 제안 템플릿
  - type : textarea
    attribute:
      value: |
        ## 📝 제안 배경
        **어떤 문제**를 해결하고 싶으신가요?  
        (예: 성능 개선, 새로운 기능 추가 등)
    - type : textarea
      attribute:
        value: |
         ## 🌟 제안된 아이디어
        - 제안하시는 아이디어를 간단히 설명해주세요.
          - 주요 기능:
            1. ...
            2. ...
          - 기대 효과:
            - [ ] 성능 개선
            - [ ] 사용자 경험 개선
    - type : textarea
      attribute:
        value: |
          ## 📖 참고 자료
          - 관련 링크나 참고할 자료를 여기에 추가하세요.
            - 예: [링크 이름](https://example.com)

